### PR TITLE
Update to the latest 2023.2

### PR DESCRIPTION
**Pull request by maosmurf**

### CODE REVIEW

**Comment by adamzanyline** [comment]
I confirm the version suggested works locally (after `./gradlew build` ) and installing plugin "from disk" to IntelliJ 2023.2 (Build #IU-232.8660.185, built on July 26, 2023)

**Comment by ikorennoy** [comment]
Hi @maosmurf!

Thank you very much for the PR.

**Comment by maosmurf** [comment]
I managed to reproduce, however no clue as how to fix, yet.
Next approach would be to learn from other plugins, most of which moved to gradle8. Will invest time next week.

**Comment by maosmurf** [comment]
Updated to gradle 8 ( `./gradlew wrapper --gradle-version 8.3` ) , now the plugin builds and runs tests also on my Windows machine.

**Comment by ikorennoy** [comment]
@maosmurf, now it works, thank you!

**Pull request merged**
